### ISSUE TITLE
Concurrency Bugs

### ISSUE THREAD

**Issue by ppashakhanloo** [sendgrid/smtpapi-csharp#101]
I have found a number of concurrency bugs in the following methods. When any of the following methods is run in two threads in parallel, there is a potential race condition.

1. 
```csharp
SendGrid.SmtpApi.HeaderSettingsNode.AddSetting(System.Collections.Generic.List<System.String>,System.Object)
```

2. 
```csharp
SendGrid.SmtpApi.HeaderSettingsNode.AddArray(System.Collections.Generic.List<System.String>,System.Collections.Generic.IEnumerable<System.Object>)
```

3.
```csharp
SendGrid.SmtpApi.HeaderSettingsNode.GetArray(System.Collections.Generic.List<System.String>)
```

**Comment by childish-sambino** [comment]
Yes, that is correct. The header settings were not designed for multi-threaded use. My worry with making it thread-safe is what happens on collisions. Suppose you set the same setting to different values in different threads. Which one should "win"? I think it's best to use separate header instances for each thread.
