### ISSUE TITLE
Not able to send multiple email to multiple recipient with same cc email address.

### ISSUE THREAD

**Issue by PrashantVasava** [sendgrid/smtpapi-csharp#104]
I want to send multiple emai; to multiple recipients with same cc email address.

            SendGrid.Helpers.Mail.SendGridMessage msg = SendGrid.Helpers.Mail.MailHelper.CreateMultipleEmailsToMultipleRecipients(from, tos, subjects, "None", sendemails.EmailBody, substitutes);
            if (sendemails.Cc != null && sendemails.Cc.Any())
            {
                var Ccs = sendemails.Cc.Select(x => new SendGrid.Helpers.Mail.EmailAddress(x)).ToList();
                for (int index = 0; index < sendemails.Receipients.Count; index++)
                {
                    msg.AddCcs(Ccs, index);
                }
            }

So, here i have to add same cc addresses to all personalization. But in this case only one email is received by email id in CC. My requirement is to sent all emails to the email id in Cc.

**Comment by JenniferMah** [comment]
@PrashantVasava
Can you include which version of c# and smtpapi-csharp you are using?
