### ISSUE TITLE
Emails getting deduped with different personalizations

### ISSUE THREAD

**Issue by tastyDanish** [sendgrid/smtpapi-csharp#105]
I'm using the MailHelper.CreateMultipleTemplateEmailsToMultipleRecipients function to create multiple emails with their own personalizations. I'm having an issue where an email address could be in more than one of these emails and its getting deduped out. I would have assumed that with different personalizations the emails would be sent anyway. Do I need to do something extra in order to ensure these emails are sent?

**Comment by JenniferMah** [comment]
Hi @tastyDanish
Could you provide more details, code samples, and links for what you're trying to accomplish? Are you using the [Sendgrid smtpapi-csharp](https://github.com/sendgrid/smtpapi-csharp) library or [Sendgrid-csharp ](https://github.com/sendgrid/sendgrid-csharp)library?

**Comment by tastyDanish** [comment]
Hi @JenniferMah thank you for the quick response. It looks like I have the wrong library. Thank you for pointing me in the right direction.
