### ISSUE TITLE
Refactor to JSON.net and simplify the code

### ISSUE THREAD

**Issue by brandonmwest** [sendgrid/smtpapi-csharp#14]
For example, this library [SendGridSharp](https://github.com/shibayan/SendGridSharp/blob/master/SendGridSharp/SmtpHeader.cs) has a much cleaner way of doing things.

**Comment by leonpw** [comment]
I will check into this

**Comment by thinkingserious** [comment]
Hi @leonpw,

That's awesome!

Could you please take a moment to [sign our CLA](https://github.com/sendgrid/smtpapi-csharp/blob/master/CONTRIBUTING.md#cla) so that we will be able to merge your changes? Thanks!

**Comment by thinkingserious** [comment]
Hi @leonpw,

Are you still planning to submit a PR? Thanks!

With Best Regards,

Elmer

**Comment by leonpw** [comment]
Hey @thinkingserious ,

Isn't the PR already merged in #26 ?

**Comment by thinkingserious** [comment]
Yes, thanks @leonpw :)
