### ISSUE TITLE
Taking a long time to load

### ISSUE THREAD

**Issue by leemcmullen** [sendgrid/smtpapi-csharp#15]
Taken from my StackOverflow question: http://stackoverflow.com/questions/29103061/sendgrid-smtp-api-dll-taking-a-long-time-to-load

> I have an ASP.NET MVC app built with VS 2013.

> I have included the SendGrid C# library via NUGET. All installed and works perfectly. The following versions are reported by Package Manager:

> `SendGrid 5.1.0`

> `SendGrid.SmtpApi 1.2.1`

> My problem is that whenever I start the application locally, it's taking a long time to load the SendGrid SMPT API. In VS I see the following in the status bar along the bottom:

> Loading symbols for SendGrid.SmtpApi.dll

> It then hangs there for up to about 30 seconds until it finally finishes and the browser finishes loading.

> Admittedly not a huge problem on it's own but becomes a pain when doing that operation many times per day.

> Is anyone else getting this? Is there anything I can do to speed it up?

**Comment by leemcmullen** [comment]
Hey @brandonmwest! You mentioned the following on StackOverflow:

> It's probably a bad path to the symbol file. 

Is there any way to verify this? If it's just a bad path somewhere then that sounds like there could be a straightforward fix?

This 30 second delay every time I run my project is killing me! Any idea if what you suggested about the bad path might be the cause?

If you could point me in the right direction then I'll happily take a look.

**Comment by brandonmwest** [comment]
Give this a try for now: http://stackoverflow.com/questions/869168/prevent-visual-studio-from-trying-to-load-symbols-for-a-particular-dll

**Comment by leemcmullen** [comment]
That's great, thanks Brandon.

**Comment by mcse3010** [comment]
It is trying to load the symbols from \\psf\home\SendGrid\smtpapi-csharp\Smtpapi\Smtpapi\SendGrid.SmtpApi.pdb

The delay in loading is it is trying to resolve the network path \\psf

**Comment by janvanderhaegen** [comment]
\psf\home\SendGrid\smtpapi-csharp\Smtpapi\Smtpapi\SendGrid.SmtpApi.pdb
I get the exact same path.

Explicitly adding SendGrid.SmtpApi.dll and SendGrid.dll to the Tools->Options->Debugging->Symbols->Excluded Symbols sped up my application startup time by 30 seconds.

**Comment by brandonmwest** [comment]
This is something I've tried to solve a few times but I'm having no luck.
Some guidance on where to look to find the offending path in the .csproj or
.sln, or a pull request, would be very much appreciated.

**Comment by thinkingserious** [comment]
Thanks for providing the solution @janvanderhaegen!
