### ISSUE TITLE
Thread safe

### ISSUE THREAD

**Issue by bolix** [sendgrid/smtpapi-csharp#16]
Is this library thread safe? Also, do you have an example on how the Async call would work on a multi-thread program?

**Comment by brandonmwest** [comment]
This library is responsible for building the headers and should be thread safe, but it contains no async calls. For the sendgrid-csharp library, the next release (coming soon) will be thread safe. You can use async calls in multiple threads but you probably won't see much additional benefit above what the async i/o provides.
