### ISSUE TITLE
SmtpApi trying to load symbols from network share path, slowing start with 60 sec (timeout).

### ISSUE THREAD

**Issue by Mobsan** [sendgrid/smtpapi-csharp#20]
SendGrid.SmtpApi is trying to load symbols from network share, which is slowing the start.

The path it is trying to load is:
\\psf\home\SendGrid\xsmtpapi\smtpapi\smtpapi\obj\release\SendGripd.SmtpApi.dll

I am using dll's from Nuget, version 1.3.1

![skjermbilde 2016-03-19 12 38 45](https://cloud.githubusercontent.com/assets/1628808/13898602/c18770f4-edd6-11e5-876c-98d37ccc81de.png)

**Comment by thinkingserious** [comment]
Hello @Mobsan,

Thanks for letting us know about this issue.

I can not re-create this on my machine and I have not been able to find a solution searching the web. Do you have any ideas on how we can fix this?

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
It looks like janvanderhaegen found a solution: https://github.com/sendgrid/smtpapi-csharp/issues/15#issuecomment-133627670

Please let us know if that works for you.
