### ISSUE TITLE
Missing destination email C# while using X-SMTPAPI header

### ISSUE THREAD

**Issue by Femilshajin** [sendgrid/smtpapi-csharp#22]
Hi,
I'm trying to send email using SendGrid library  in c#. When I try to send email using this code(In console application). I'm receiving the error as "missing destination email". I have specified the destination mail in the header. What am I doing Wrong??

          try {
                var header = new Header();

                var recipients = new List<String> { "destination@xxx.com"};
                header.SetTo(recipients);

                var xmstpapiJson = header.JsonString();

                var myMessage = new SendGridMessage();
                myMessage.From = new MailAddress("from@yyy.com");
                myMessage.Subject = "this is a test email.";
                myMessage.Text = "this is my test email body";

                // add the custom header that we built above
                myMessage.Headers.Add("X-SMTPAPI", xmstpapiJson);

                var transportWeb = new SendGrid.Web("API KEY");
                transportWeb.DeliverAsync(myMessage).Wait();

            }
            catch(Exception e)
            {
                    return;
            }

**Comment by thinkingserious** [comment]
Could you please try using our SMTPAPI library to set the destination email? https://github.com/sendgrid/smtpapi-csharp

**Comment by thinkingserious** [comment]
Hello @Femilshajin,

I suggest you verify the output of xmstpapiJson and that it conforms to this format: https://sendgrid.com/docs/API_Reference/SMTP_API/index.html

Also, with our new v3 /mail/send endpoint: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html, you no longer need to pass in an SMTPAPI header. Our new library, to be out of beta in a few weeks will support it. You can check out the new library here: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta

Thank you for your support!

With Best Regards,

Elmer
