### ISSUE TITLE
SMTP server removes sequences.

### ISSUE THREAD

**Issue by Bartmax** [sendgrid/smtpapi-csharp#23]
I'm not sure where to file this issue, if this is not the correct repo, please point me to it.

When using sendgrid via `smtp.sendgrid.net` sequences get removed. Here is the code i'm using.

```
var msg = $@"This message
spans multiple
lines

Greetings!
";

message.Body = new TextPart("plain") { Text = msg };
using (var client = new SmtpClient())
{
    await client.ConnectAsync("smtpserver", 587, SecureSocketOptions.Auto);
    await client.AuthenticateAsync("user", "pass");
    await client.SendAsync(message);
    await client.DisconnectAsync(true);
}
```

When using gmail smtp server, when I look at the email on gmail web client, I see the lines as they were sent.

I then switched to sendgrid smtp server, and at the same client (gmail web) i see the email as one liner, like this:

```
This message spans multiple lines 
Greetings!
```

At first I filled the issue at MailKit (the library I'm using) and the response from that library author (who is an expert on mail) suggest that the problem is on the sendgrid end. 

Here's the original comment on the issue:
https://github.com/jstedfast/MailKit/issues/380#issuecomment-239127411

Is there anyway to sendgrid fix this on their end or is something else going on?

**Comment by thinkingserious** [comment]
Hello @Bartmax,

I apologize for the looooong delayed response :(

I am doing some housekeeping and I found this issue. Is this still an issue for you?

With Best Regards,

Elmer

**Comment by Bartmax** [comment]
Yes, this is still an issue. I workaround it but I still think is a bug on sendgrid end

**Comment by thinkingserious** [comment]
Thanks @Bartmax!

I will pass this along to the API team for review.

**Comment by eshanholtz** [comment]
Closing as this was marked as a non-library issue.
