### ISSUE TITLE
Error during mail merge: "A recipient must be specified"

### ISSUE THREAD

**Issue by FranciscoG** [sendgrid/smtpapi-csharp#24]
When I try to do something similar to the mail merge type you have as an example I always get this error:  `"A recipient must be specified"`

Am I supposed to also be using a "To" field in the MailMessage?

the [docs](https://sendgrid.com/docs/API_Reference/SMTP_API/using_the_smtp_api.html) specifically tell you NOT to include the TO field

> When using the X-SMTPAPI to send to multiple recipients, you cannot use the standard SMTP protocols “TO” field to send to multiple recipients because doing so can generate duplicate messages to the addresses listed in both. 

Also I just want to confirm that the smtpapi-csharp library will handle wrapping so I don't exceed the 1000 character line length limit.  

My code looks very similar to this except I'm generating much much larger lists 

``` csharp
var header = new Header();

// I'm sending out about 4K recipients
var recipients = new List<String> {"test1@example.com", "test2@example.com", "test3@example.com"};
header.SetTo(recipients);

// I have 4 different subs instead of 1
var subs = new List<String> {"A","B","C"};
header.AddSubstitution("%name%", subs);

var mail = new MailMessage
{
    From = new MailAddress("test@example.com"),
    Subject = "Welcome",
    Body = "Hi there %name%"
};

// add the custom header that we built above
mail.Headers.Add("X-SMTPAPI", header.JsonString());

var client = new SmtpClient
{
    Port = 587,
    Host = "smpt.sendgrid.net",
    Timeout = 10000,
    DeliveryMethod = SmtpDeliveryMethod.Network,
    UseDefaultCredentials = false,
    Credentials = System.Net.NetworkCredential(username,password);
}
client.SendMailAsync(mail, null)
mail.Dispose()
```

**Comment by thinkingserious** [comment]
Hello @FranciscoG,

Thanks for submitting this issue in detail. I've added this to our backlog for review.

**Comment by FranciscoG** [comment]
thanks!  

also want to make sure that this question doesn't go unnoticed in that message above:

> Also I just want to confirm that the **smtpapi-csharp** library will handle wrapping so I don't exceed the 1000 character line length limit.

**Comment by yofang** [comment]
@thinkingserious, is there any update on this?
I met exactly the same issue.

**Comment by thinkingserious** [comment]
@yofang,

Not yet, this is still in our backlog. However, I've added your vote to the issue to help move it up the queue.

**Comment by thinkingserious** [comment]
Hello everyone,

I'm still trying to find and answer for this.

In the mean time, the new C# library v9 allows for easy mail merge:
https://github.com/sendgrid/sendgrid-csharp/blob/v9beta/tests/SendGrid.Tests/Integration.cs#L331

You can try it out via Nuget here: https://www.nuget.org/packages/Sendgrid/9.0.4-beta

**Comment by FranciscoG** [comment]
It looks like you just need to add a "To" in the construction of a `MailMessage`, then it works! It just ignores it because you've used `header.SetTo()`.  I'm guessing because `SmtpClient.SendMailAsync` requires the `To` field from `MailMessage`.

so in my original example at the top of this issue I would add
```csharp
var mail = new MailMessage
{
    From = new MailAddress("test@example.com"),
    Subject = "Welcome",
    Body = "Hi there %name%",
   
    // add the "To" field but it will be ignored if you're using a SetTo list
    To = new MailAddress("ignored@email.com")
};
```

This worked for me.  I used a different email in the `MailMessage.To` but when I tested it I got the proper emails in my recipients list with the proper subsitutions.

### Please do some of your own testing to corroborate this. If this solution works for others as well then we can close this issue and call it solved

## Warning

Be aware that it still includes that email somewhere in the headers of your email message.  A user won't see it unless they go poking around in the email's source headers.  Just don't use an email that you don't want public. If this is a concern for you then be warned! Use an email you don't care about, maybe the same one as your "From".

I found that email used for testing in a block of text in my email message's header that looked something like this
```
Received: from BLA-BLA (unknown [redacted ip address])
	by blablabla.sendgrid.net (SG) with ESMTP id ########
	for <ignored@email.com>; Thu, 14 Dec 2017 00:20:46.860 +0000 (UTC)
```

**Comment by thinkingserious** [comment]
Hi @FranciscoG,

Thanks for taking the time to provide the solution!

With Best Regards,

Elmer
