### ISSUE TITLE
Cannot specify more than one BCC recipient

### ISSUE THREAD

**Issue by benmiller86** [sendgrid/smtpapi-csharp#25]
You will have to forgive me if this has been added in a later version, but I am stuck using 1.1.3.0 as I need .net 4.0 support. 

I can't see a way of adding more than one address to the BCC filter. I can quite happily add a single address like this:

```
var header = new SendGrid.SmtpApi.Header();
header.AddFilterSetting("bcc", new List<string>() { "enable" }, "1");
header.AddFilterSetting("bcc", new List<string>() { "email" }, "address1@domain.com");
Console.WriteLine(header.JsonString());
```

which will output:

```
{
    "filters": {
        "bcc": {
            "settings": {
                "enable": "1",
                "email": "address1@domain.com"
            }   
        }
    }
}
```

An array is required for multiple BCC recipients, like this:

```
{
    "filters": {
        "bcc": {
            "settings": {
                "enable": "1",
                "email": ["address1@domain.com", "address2@domain.com"]
            }   
        }
    }
}
```

But there is only one overload for the `.AddFilterSetting()` method, and anything I enter as the last argument is wrapped in quotes so I can't even pop the JSON array in myself.

If there is a way around this that someone could point to that would be awesome, otherwise it may be worth looking in to if you have time.

Thanks!

**Comment by thinkingserious** [comment]
Hello @benmiller86,

The BCC filter only accepts one email: https://sendgrid.com/docs/API_Reference/SMTP_API/apps.html#bcc

I'm happy to put in a feature request for you if you like.
