### ISSUE TITLE
message-ID

### ISSUE THREAD

**Issue by MOSFETTECH** [sendgrid/smtpapi-csharp#27]
I dont even know if this is an issue, however support directed me here.

About tracking a particular e-mail this is what they suggested: 

_For a more comprehensive collection of data, I would suggest using the Event Notification app. This will allow you to gather all the data you need. You will be able to filter the emails by message-ID or recipient addresses._

And I said; 

_Looks like Event Notification app will solve my problem.
However, with following code I cannot retrieve any message-ID as return;
which service should I use to recieve message-ID in return ?_

```
dynamic sg = new SendGridAPIClient(SendGridApiKey);
 .... //setting recipients, sender and mail body.
var mail = new SendGrid.Helpers.Mail.Mail(from, subject, to, content);
dynamic response = await sg.client.mail.send.post(requestBody: mail.Get());
```
Currently this is how I send email, and response has no value of message-ID or something  close.

So, what do I miss ?

cheers,

emre

**Comment by thinkingserious** [comment]
Hello @MOSFETTECH,

It looks like you are using our sendgrid-csharp library, which is located [here](https://github.com/sendgrid/sendgrid-csharp).

You should be able to retrieve the Message-ID in the headers, like so: https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/Example/Example.cs#L112

Also, you can set your own custom arguments like so: https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/Example/Example.cs#L235

I hope that helps.

With Best Regards,

Elmer

**Comment by MOSFETTECH** [comment]
Thanks a lot Elmer!

I got what i needed with the example you linked.

Best wishes,

Emre
