### ISSUE TITLE
sendgrid.web(credentials).deliver doesn't work with api key credentials

### ISSUE THREAD

**Issue by jigar8888** [sendgrid/smtpapi-csharp#29]
sendgrid.web(credentials).deliver works with original credentials but doesn't work with api key credentials.

Sample code is here.

            SendGridMessage myMessage = new SendGridMessage();
            myMessage.AddTo(MailTo);
            myMessage.From = new MailAddress(MailFrom, "Muses");
            myMessage.Html = "<p></p> ";            
            myMessage.Subject = " ";
            //myMessage.EnableTemplate("<p> <% body %> Hello</p>");
            if (Subject.ToLower() == "Reset_Password".ToLower())
            {
                myMessage.EnableTemplateEngine("442ce4ed-e016-466d-b6f1-eef94bb8b704");
            }
            else if (Subject.ToLower() == "InviteToGroup".ToLower())
            {
                myMessage.EnableTemplateEngine("a58b3bb7-bf82-4d95-98af-be124d24fd1c");
            }            
            myMessage.AddSubstitution("{{CALLBACKURL}}", new List<string> { CallBackURL });
            myMessage.AddSubstitution("{{USERNAME}}", new List<string> { userName });
            // Create credentials, specifying your user name and password.
            var credentials = new System.Net.NetworkCredential("apikey", "api key password");
            var transportWeb = new SendGrid.Web(credentials);
            transportWeb.Deliver(myMessage);

**Comment by thinkingserious** [comment]
Hello @jigar8888,

If you would like to use your API Key for authentication, please use our [official C# .NET SDK](https://github.com/sendgrid/sendgrid-csharp/).

Thanks!

With Best Regards,

Elmer

**Comment by jigar8888** [comment]
thanks..
