### ISSUE TITLE
TravisCI Issue with nuget

### ISSUE THREAD

**Issue by mbernier** [sendgrid/smtpapi-csharp#43]
Travis is reporting:

```
Unable to find version '1.1.10' of package 'Microsoft.Bcl'.
The command "nuget restore Smtpapi/SendGrid.SmtpApi.sln" failed and exited with 1 during .
```

https://travis-ci.org/sendgrid/smtpapi-csharp/builds/291661357?utm_source=github_status&utm_medium=notification

**Comment by bvdwalt** [comment]
Hi @mbernier, this seems to have been an intermittent issue with nuget, but it has not happened again since.
