### ISSUE TITLE
Warning: 3 References not resolved 

### ISSUE THREAD

**Issue by mbernier** [sendgrid/smtpapi-csharp#69]
#### Issue Summary

```
Warnings:
/home/travis/build/sendgrid/smtpapi-csharp/Smtpapi/SendGrid.SmtpApi.sln (default targets) ->
(Build target) ->
/home/travis/build/sendgrid/smtpapi-csharp/Smtpapi/Smtpapi/SendGrid.SmtpApi.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveAssemblyReferences target) ->
	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Net.Http, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL' not resolved
	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Net.Http.Extensions, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL' not resolved
	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL' not resolved
```

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* smtpapi-csharp Version: master (latest commit: [commit number])
* Platform (WebForms, ASP.NET, ASP.NET Core, etc.)
* .NET Version: 4.5.2

**Comment by nicolastarzia** [comment]
I saw the references in portable project, but I removed the references and warning goes on.

Why System.Net.Http is referenced in this project?

**Comment by thinkingserious** [comment]
Hi @nicolastarzia,

That reference is removed in PR #73, we just have not merged/deployed it yet. 

With Best Regards,

Elmer
