### ISSUE TITLE
Invalid symbol path compiled into SendGrid.SmtpApi.dll

### ISSUE THREAD

**Issue by michaelharrod** [sendgrid/smtpapi-csharp#7]
Hi there, I'm a novice when it comes to GitHub, NuGet and debug symbols so apologies if this is the wrong place to report this, but we recently added the SendGrid NuGet package and its required dependency SendGrid.SmtpApi to our C# project and have been having some real slowdowns when building and running our project.

After a bit of digging I found that Visual Studio seems to be trying to access a path we don't have here:
\\psf\home\SendGrid\xsmtpapi\Smtpapi\Smtpapi\obj\Release\SendGrid.SmtpApi.pdb

Visual Studio is getting a network timeout before proceeding and we're waiting for this to happen every time we run the project. This path seems to have been compiled into the assembly.

I managed to work around this changing Visual Studio options to exclude this module from symbol loading, but I thought it would be worthwhile for this to be adjusted in an upcoming release in case this causes issue for other developers.

Cheers,

Michael

Output of dumbin /headers below:
--

Microsoft (R) COFF/PE Dumper Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file SendGrid.SmtpApi.dll

PE signature found

File Type: DLL

FILE HEADER VALUES
             14C machine (x86)
               3 number of sections
        537D236D time date stamp Thu May 22 10:06:37 2014
               0 file pointer to symbol table
               0 number of symbols
              E0 size of optional header
            2102 characteristics
                   Executable
                   32 bit word machine
                   DLL

OPTIONAL HEADER VALUES
             10B magic # (PE32)
           11.00 linker version
            1E00 size of code
             600 size of initialized data
               0 size of uninitialized data
            3D6E entry point (10003D6E)
            2000 base of code
            4000 base of data
        10000000 image base (10000000 to 10007FFF)
            2000 section alignment
             200 file alignment
            4.00 operating system version
            0.00 image version
            4.00 subsystem version
               0 Win32 version
            8000 size of image
             200 size of headers
            FA1E checksum
               3 subsystem (Windows CUI)
            8540 DLL characteristics
                   Dynamic base
                   NX compatible
                   No structured exception handler
                   Terminal Server Aware
          100000 size of stack reserve
            1000 size of stack commit
          100000 size of heap reserve
            1000 size of heap commit
               0 loader flags
              10 number of directories
               0 [       0] RVA [size] of Export Directory
            3D14 [      57] RVA [size] of Import Directory
            4000 [     348] RVA [size] of Resource Directory
               0 [       0] RVA [size] of Exception Directory
               0 [       0] RVA [size] of Certificates Directory
            6000 [       C] RVA [size] of Base Relocation Directory
            3BDC [      1C] RVA [size] of Debug Directory
               0 [       0] RVA [size] of Architecture Directory
               0 [       0] RVA [size] of Global Pointer Directory
               0 [       0] RVA [size] of Thread Storage Directory
               0 [       0] RVA [size] of Load Configuration Directory
               0 [       0] RVA [size] of Bound Import Directory
            2000 [       8] RVA [size] of Import Address Table Directory
               0 [       0] RVA [size] of Delay Import Directory
            2008 [      48] RVA [size] of COM Descriptor Directory
               0 [       0] RVA [size] of Reserved Directory

SECTION HEADER #1
   .text name
    1D74 virtual size
    2000 virtual address (10002000 to 10003D73)
    1E00 size of raw data
     200 file pointer to raw data (00000200 to 00001FFF)
       0 file pointer to relocation table
       0 file pointer to line numbers
       0 number of relocations
       0 number of line numbers
60000020 flags
         Code
         Execute Read

  Debug Directories

        Time Type       Size      RVA  Pointer
    -------- ------ -------- -------- --------
    537D236D cv          11C 00003BF8     1DF8    Format: RSDS, {06873E5B-202B-457D-BE32-C6740EB9D8D1}, 2, \\psf\home\SendGrid\xsmtpapi\Smtpapi\Smtpapi\obj\Release\SendGrid.SmtpApi.pdb

SECTION HEADER #2
   .rsrc name
     348 virtual size
    4000 virtual address (10004000 to 10004347)
     400 size of raw data
    2000 file pointer to raw data (00002000 to 000023FF)
       0 file pointer to relocation table
       0 file pointer to line numbers
       0 number of relocations
       0 number of line numbers
40000040 flags
         Initialized Data
         Read Only

SECTION HEADER #3
  .reloc name
       C virtual size
    6000 virtual address (10006000 to 1000600B)
     200 size of raw data
    2400 file pointer to raw data (00002400 to 000025FF)
       0 file pointer to relocation table
       0 file pointer to line numbers
       0 number of relocations
       0 number of line numbers
42000040 flags
         Initialized Data
         Discardable
         Read Only

  Summary

        2000 .reloc
        2000 .rsrc
        2000 .text

**Comment by brandonmwest** [comment]
Thanks for this, working on a new release and will address.
